name: visit_albania
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.8
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  google_fonts: ^6.2.1
  flutter_map: ^8.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.6.1
  country_picker: ^2.0.27
  provider: ^6.1.5
  phone_number_text_input_formatter: ^0.0.2
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/places.json
    - assets/images/
  
  