// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC9vA6wC9C3a-sq30BYM7Rgpakx_DabG8',
    appId: '1:1003168161955:web:acf94e45bd11b2e044df16',
    messagingSenderId: '1003168161955',
    projectId: 'travel-app-25aeb',
    authDomain: 'travel-app-25aeb.firebaseapp.com',
    storageBucket: 'travel-app-25aeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT5h5UPoyy_jd9is_Mg5-acH7v3WjYgJ4',
    appId: '1:1003168161955:android:52da2779b3a17fbe44df16',
    messagingSenderId: '1003168161955',
    projectId: 'travel-app-25aeb',
    storageBucket: 'travel-app-25aeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zHuxB_4vIH4GQBBYBewTKk8fqyh73Mw',
    appId: '1:1003168161955:ios:ba074d9e8e05bfe744df16',
    messagingSenderId: '1003168161955',
    projectId: 'travel-app-25aeb',
    storageBucket: 'travel-app-25aeb.firebasestorage.app',
    androidClientId: '1003168161955-g4s1e886o07ne4drnaa0lt2ekncdju94.apps.googleusercontent.com',
    iosClientId: '1003168161955-92dcnbdkk1lu72seo4nrbpp4t59f907t.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitAlbania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zHuxB_4vIH4GQBBYBewTKk8fqyh73Mw',
    appId: '1:1003168161955:ios:ba074d9e8e05bfe744df16',
    messagingSenderId: '1003168161955',
    projectId: 'travel-app-25aeb',
    storageBucket: 'travel-app-25aeb.firebasestorage.app',
    androidClientId: '1003168161955-g4s1e886o07ne4drnaa0lt2ekncdju94.apps.googleusercontent.com',
    iosClientId: '1003168161955-92dcnbdkk1lu72seo4nrbpp4t59f907t.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitAlbania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC9vA6wC9C3a-sq30BYM7Rgpakx_DabG8',
    appId: '1:1003168161955:web:a922195d06a5cf5e44df16',
    messagingSenderId: '1003168161955',
    projectId: 'travel-app-25aeb',
    authDomain: 'travel-app-25aeb.firebaseapp.com',
    storageBucket: 'travel-app-25aeb.firebasestorage.app',
  );
}
